Implement input textarea and adding typography-border color
helloproclub/Pinoccio pull request #24
Opened 2020-05-21 23:24 UTC by lovanto

2020-05-26 11:49 UTC, BlinfoldKing commented
warnnya ngikutin design ya

2020-05-26 12:31 UTC, lovanto commented
udh gk conflic & warna font udh sama seperti desain

2020-05-27 13:03 UTC, blinfoldking requested changes

2020-05-27 13:03 UTC, BlinfoldKing commented on src/components/TextArea/index.js
> +            <span className="textarea-name">{textAreaName}</span>
ini diset cuman muncul kalo textAreaName !== undefined atau ""

2020-05-27 13:19 UTC, lovanto commented on src/components/TextArea/index.js
> +            <span className="textarea-name">{textAreaName}</span>
maksudnya ditambah kondisi "if textAreaName !== null"  di bawah cons ?

2020-06-01 06:39 UTC, merged